name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout event-plugin 仓库
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. 给 gradlew 授权
      - name: Make gradlew executable
        run: chmod +x ./event-plugin/gradlew

      # 4. 修改 kafkaplugin build.gradle，生成独立 JAR 并打包 ZIP
      - name: Patch kafkaplugin build.gradle
        run: |
          cat >> event-plugin/plugins/kafkaplugin/build.gradle << 'EOF'
          task jarPlugin(type: Jar) {
              archiveBaseName.set('plugin-kafka')
              archiveVersion.set('1.0.0')
              from sourceSets.main.output
          }

          task zipPlugin(type: Zip) {
              dependsOn jarPlugin
              archiveBaseName.set('plugin-kafka')
              archiveVersion.set('1.0.0')
              from(zipTree(jarPlugin.archiveFile.get().asFile)) {
                  into('plugins/kafkaplugin')
              }
              from(sourceSets.main.runtimeClasspath) {
                  into('plugins/kafkaplugin/lib')
              }
          }

          build.dependsOn zipPlugin
          EOF

      # 5. 编译 kafkaplugin 并生成 JAR+ZIP
      - name: Build kafkaplugin
        working-directory: event-plugin
        run: ./gradlew clean :plugins:kafkaplugin:zipPlugin -x test

      # 6. 查看生成文件
      - name: List built files
        run: |
          ls -lh plugins/kafkaplugin/build/libs/

      # 7. 上传 JAR 和 ZIP 作为 artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-artifacts
          path: |
            event-plugin/plugins/kafkaplugin/build/libs/plugin-kafka-1.0.0.jar
            event-plugin/plugins/kafkaplugin/build/libs/plugin-kafka-1.0.0.zip
