name: Build Event Plugin ZIP

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ "main" ]  # 自动触发也支持

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout event-plugin 源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. 构建核心插件 JAR
      - name: Build core JAR
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          ls -lh event-plugin-core/build/libs

      # 4. 打包插件 ZIP
      - name: Package plugin-kafka-1.0.0.zip
        working-directory: event-plugin
        run: |
          mkdir -p build/plugins/plugin-kafka-1.0.0
          cp event-plugin-core/build/libs/event-plugin-core-*.jar build/plugins/plugin-kafka-1.0.0/plugin-kafka-1.0.0.jar
          cd build/plugins
          zip -r plugin-kafka-1.0.0.zip plugin-kafka-1.0.0
          ls -lh plugin-kafka-1.0.0.zip

      # 5. 上传 ZIP 作为 artifact
      - name: Upload plugin ZIP
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-1.0.0
          path: event-plugin/build/plugins/plugin-kafka-1.0.0.zip
