name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取官方源码
      - name: Checkout official event-plugin
        uses: actions/checkout@v3
        with:
          repository: tronprotocol/event-plugin
          path: event-plugin
          fetch-depth: 1

      # 2. 设置 JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      # 3. 降级 Kafka 客户端到 3.4.0
      - name: Downgrade Kafka client to 3.4.0
        run: |
          FILE="event-plugin/plugins/kafkaplugin/build.gradle"
          if [ -f "$FILE" ]; then
              sed -i 's/org.apache.kafka:kafka-clients:3.9.1/org.apache.kafka:kafka-clients:3.4.0/' "$FILE"
              echo "Kafka client version changed to 3.4.0"
              cat "$FILE"
          else
              echo "File $FILE not found, skipping"
          fi

      # 4. 构建普通 JAR
      - name: Build Event Plugin JAR
        run: |
          cd event-plugin
          ./gradlew clean build :plugins:kafkaplugin:jar

      # 5. 上传 JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin
          path: event-plugin/plugins/kafkaplugin/build/libs/*.jar
