name: Build Event Plugin with Kafka JAR

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout官方event-plugin源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. 给gradlew授权
      - name: Make gradlew executable
        run: chmod +x ./event-plugin/gradlew

      # 4. 修改kafkaplugin build.gradle生成独立JAR并放入ZIP
      - name: Patch kafkaplugin to produce JAR and ZIP
        run: |
          cat >> event-plugin/plugins/kafkaplugin/build.gradle <<EOF

// 生成 plugin-kafka-1.0.0.jar
task jarPlugin(type: Jar) {
    archiveBaseName.set('plugin-kafka')
    archiveVersion.set('1.0.0')
    from sourceSets.main.output
}

// 将 JAR 和依赖打包到 ZIP
task zipPlugin(type: Zip) {
    dependsOn jarPlugin
    archiveBaseName.set('plugin-kafka')
    archiveVersion.set('1.0.0')
    from(zipTree(jarPlugin.archiveFile)) {
        into('plugins/kafkaplugin')
    }
    from(configurations.runtimeClasspath) {
        into('plugins/kafkaplugin/lib')
    }
}

build.dependsOn zipPlugin
EOF

      # 5. 构建插件
      - name: Build Event Plugin
        working-directory: event-plugin
        run: ./gradlew clean build -x test

      # 6. 查看生成文件
      - name: List built files
        run: |
          echo "Listing kafkaplugin/libs:"
          ls -lh plugins/kafkaplugin/build/libs/
          echo "Listing plugin ZIP:"
          ls -lh plugins/kafkaplugin/build/distributions/

      # 7. 上传 ZIP 和 JAR 作为 artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin-artifacts
          path: |
            plugins/kafkaplugin/build/distributions/plugin-kafka-1.0.0.zip
            plugins/kafkaplugin/build/libs/plugin-kafka-1.0.0.jar
