name: Build Latest Event Plugin

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取 event-plugin 官方源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk

      # 3. 构建 Kafka 插件 (完整 zip)
      - name: Build Kafka Plugin
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew :plugins:kafkaplugin:clean :plugins:kafkaplugin:distZip -x test
          echo "=== Zip Files ==="
          ls -lh plugins/kafkaplugin/build/distributions

      # 4. 解压 Kafka 插件 (得到 jar + lib + plugin.conf)
      - name: Unzip Kafka Plugin
        working-directory: event-plugin/plugins/kafkaplugin/build
        run: |
          mkdir unpacked
          unzip distributions/kafkaplugin-*.zip -d unpacked
          echo "=== Unpacked Content ==="
          ls -R unpacked

      # 5. 上传 zip 和解压目录
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kafkaplugin-artifacts
          path: |
            event-plugin/plugins/kafkaplugin/build/distributions/*.zip
            event-plugin/plugins/kafkaplugin/build/unpacked/**
