name: Build Latest Event Plugin

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取 event-plugin 官方源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk

      # 3. 构建整个插件
      - name: Build Event Plugin
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean buildPlugin -x test
          echo "=== Plugin ZIPs ==="
          ls -lh build/plugins || true

      # 4. 解压 Kafka 插件
      - name: Unzip Kafka Plugin
        working-directory: event-plugin/build
        run: |
          mkdir unpacked
          unzip plugins/kafkaplugin-*.zip -d unpacked
          echo "=== Unpacked Content ==="
          ls -R unpacked

      # 5. 上传构建产物
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kafkaplugin-artifacts
          path: |
            event-plugin/build/plugins/kafkaplugin-*.zip
            event-plugin/build/unpacked/**
