name: Build Event Plugin JAR and ZIP

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 官方 event-plugin 源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      # 3. 给 gradlew 授权
      - name: Make gradlew executable
        run: chmod +x ./event-plugin/gradlew

      # 4. 修改 kafkaplugin build.gradle，生成独立 JAR
      - name: Patch kafkaplugin to produce JAR
        run: |
          echo "
          task jarPlugin(type: Jar) {
              archiveBaseName.set('plugin-kafka')
              archiveVersion.set('1.0.0')
              from sourceSets.main.output
          }
          build.dependsOn jarPlugin
          " >> event-plugin/plugins/kafkaplugin/build.gradle

      # 5. 编译 kafkaplugin 并生成 JAR
      - name: Build kafkaplugin JAR
        working-directory: event-plugin
        run: ./gradlew clean :plugins:kafkaplugin:jarPlugin -x test

      # 6. 查看生成文件
      - name: List built JAR
        run: ls -lh plugins/kafkaplugin/build/libs/

      # 7. 创建 FullNode 可加载 ZIP（包含依赖）
      - name: Create plugin ZIP with dependencies
        working-directory: event-plugin/plugins/kafkaplugin
        run: |
          mkdir -p build/plugin
          # 复制主 JAR
          cp build/libs/plugin-kafka-1.0.0.jar build/plugin/
          # 收集依赖 JAR 到 lib
          mkdir -p build/plugin/lib
          find ../../../build -name '*.jar' ! -name 'plugin-kafka-1.0.0.jar' -exec cp {} build/plugin/lib/ \;
          # 创建 plugin.properties
          echo "plugin.name=plugin-kafka" > build/plugin/plugin.properties
          echo "plugin.version=1.0.0" >> build/plugin/plugin.properties
          echo "plugin.class=org.tron.event.plugin.kafka.KafkaPlugin" >> build/plugin/plugin.properties
          # 打包成 ZIP
          cd build && zip -r plugin-kafka-1.0.0.zip plugin

      # 8. 上传 JAR 作为 artifact
      - name: Upload plugin JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-jar
          path: plugins/kafkaplugin/build/libs/plugin-kafka-1.0.0.jar

      # 9. 上传 ZIP 作为 artifact
      - name: Upload plugin ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-zip
          path: plugins/kafkaplugin/build/plugin-kafka-1.0.0.zip
