name: Build Event Plugin JAR

on:
  workflow_dispatch:  # 手动触发
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 官方 event-plugin 源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk

      # 3. 构建 kafkaplugin 模块 JAR
      - name: Build kafkaplugin JAR
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean :plugins:kafkaplugin:build -x test
          echo "Listing build output:"
          ls -lh plugins/kafkaplugin/build/libs/

      # 4. 上传构建产物
      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-jar
          path: event-plugin/plugins/kafkaplugin/build/libs/plugin-kafka-1.0.0.jar
