name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取官方源码
      - name: Checkout official event-plugin
        uses: actions/checkout@v3
        with:
          repository: tronprotocol/event-plugin
          path: event-plugin
          fetch-depth: 1

      # 2. 设置 JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8


      # 4. 构建普通 JAR
      - name: Build Event Plugin JAR
        run: |
          cd event-plugin
          ./gradlew clean build :plugins:kafkaplugin:jar

      # 5. 上传 JAR artifact
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin
          path: event-plugin/plugins/kafkaplugin/build/libs/*.jar
