name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout official event-plugin
        uses: actions/checkout@v3
        with:
          repository: tronprotocol/event-plugin
          path: event-plugin
          fetch-depth: 1

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Downgrade Kafka client to 3.4.0
        run: |
          FILE="event-plugin/kafkaplugin/build.gradle"
          if grep -q "org.apache.kafka:kafka-clients:3.9.1" "$FILE"; then
              sed -i 's/org.apache.kafka:kafka-clients:3.9.1/org.apache.kafka:kafka-clients:3.4.0/' "$FILE"
              echo "Kafka client version changed to 3.4.0"
          else
              echo "Kafka client 3.9.1 not found, skipping"
          fi
          cat "$FILE"

      - name: Build and package Event Plugin
        run: |
          cd event-plugin
          ./gradlew clean build :kafkaplugin:shadowJar

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin
          path: event-plugin/kafkaplugin/build/libs/*.jar


