name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x ./event-plugin/gradlew

      - name: Patch kafkaplugin build.gradle
        run: |
          echo "apply from: 'plugin-build.gradle'" >> event-plugin/plugins/kafkaplugin/build.gradle

      - name: Build Event Plugin
        working-directory: event-plugin
        run: ./gradlew clean :plugins:kafkaplugin:zipPlugin -x test

      - name: List ZIP file
        run: ls -lh event-plugin/plugins/kafkaplugin/build/distributions/

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-zip
          path: event-plugin/plugins/kafkaplugin/build/distributions/plugin-kafka-1.0.0.zip
