name: Build Event Plugin JAR

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master
          path: event-plugin
          submodules: recursive

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Make gradlew executable
        run: chmod +x ./event-plugin/gradlew

      - name: Create plugin-build.gradle
        run: |
          cat > event-plugin/plugins/kafkaplugin/plugin-build.gradle << 'EOF'
          afterEvaluate {
              task jarPlugin(type: Jar) {
                  archiveBaseName.set('plugin-kafka')
                  archiveVersion.set('1.0.0')
                  from sourceSets.main.output
              }

              task zipPlugin(type: Zip) {
                  dependsOn jarPlugin
                  archiveBaseName.set('plugin-kafka')
                  archiveVersion.set('1.0.0')
                  from(zipTree(jarPlugin.archiveFile)) {
                      into('plugins/kafkaplugin')
                  }
                  from(configurations.runtimeClasspath) {
                      into('plugins/kafkaplugin/lib')
                  }
              }

              build.dependsOn zipPlugin
          }
          EOF

      - name: Apply plugin-build.gradle
        run: |
          echo "apply from: 'plugin-build.gradle'" >> event-plugin/plugins/kafkaplugin/build.gradle

      - name: Build kafkaplugin
        working-directory: event-plugin
        run: ./gradlew clean :plugins:kafkaplugin:zipPlugin -x test

      - name: List generated files
        run: ls -lh event-plugin/plugins/kafkaplugin/build/distributions/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin-kafka-zip
          path: event-plugin/plugins/kafkaplugin/build/distributions/plugin-kafka-1.0.0.zip
