name: Build Latest Event Plugin JAR

on:
  workflow_dispatch:   # 手动触发
  push:
    branches: [ "main" ]  # 自动触发也支持

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 官方 event-plugin 源码到子目录
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: master        # 可改为 tag 或 commit
          path: event-plugin
          submodules: recursive  # 拉取子模块（如果有）

      # 2. 安装 JDK 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk

      # 3. 构建 Event Plugin
      - name: Build Event Plugin
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          echo "Listing plugin ZIP files:"
          ls -lh build/plugins || true
          echo "Listing event-plugin-core JAR:"
          ls -lh event-plugin-core/build/libs || true

      # 4. 上传构建产物
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin-artifacts
          path: |
            event-plugin/build/plugins/*.zip
            event-plugin/event-plugin-core/build/libs/*.jar
