name: Build Event Plugin

on:
  workflow_dispatch:
    inputs:
      tag_or_branch:
        description: 'Event Plugin tag or branch to build'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 官方源码
      - name: Checkout event-plugin
        uses: actions/checkout@v4
        with:
          repository: tronprotocol/event-plugin
          ref: ${{ github.event.inputs.tag_or_branch }}
          path: event-plugin
          submodules: recursive

      # 2. 设置 Java 1.8
      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          java-package: jdk

      # 3. 构建 event-plugin-core 和 plugin
      - name: Build Event Plugin
        working-directory: event-plugin
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test
          echo "Listing plugin ZIP files:"
          ls -lh build/plugins || true
          echo "Listing core JAR files:"
          ls -lh event-plugin-core/build/libs || true

      # 4. 上传 artifact
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: event-plugin-artifacts
          path: |
            event-plugin/build/plugins/*.zip
            event-plugin/event-plugin-core/build/libs/*.jar
